[package]
name = "snooze"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = { version = "0.1.13", default-features = false, features = ["help"] }

[dev-dependencies]
rstest = { version = "0.26.1", features = ["crate-name"], default-features = false }
